version: "3"

services:
  user:
    build:
      context: ./packages/user
      dockerfile: Dockerfile
    ports:
      - "30001:30001"
    restart: always
    env_file:
      - general.env
      - user.env
      - db.env
    networks:
      - api-internal

  auth:
    build:
      context: ./packages/auth
      dockerfile: Dockerfile
    ports:
      - "30002:30002"
    restart: always
    env_file:
      - general.env
      - auth.env
    depends_on:
      - user
    networks:
      - api-internal

  company:
    build:
      context: ./packages/company
      dockerfile: Dockerfile
    ports:
      - "30003:30003"
    restart: always
    env_file:
      - general.env
      - company.env
      - db.env
    depends_on:
      - auth
    networks:
      - api-internal

  product:
    build:
      context: ./packages/product
      dockerfile: Dockerfile
    ports:
      - "30004:30004"
    restart: always
    env_file:
      - general.env
      - product.env
      - db.env
    depends_on:
      - company
    networks:
      - api-internal

  s3:
    build:
      context: ./packages/s3
      dockerfile: Dockerfile
    ports:
      - "30005:30005"
    restart: always
    env_file:
      - general.env
      - s3.env
    depends_on:
      - product
    networks:
      - api-internal

  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: always
    env_file:
      - general.env
      - gateway.env
    depends_on:
      - s3
    networks:
      - api-internal

networks:
  api-internal:
